import assert from "node:assert/strict";
import { test } from "node:test";
import { createDecipheriv } from "node:crypto";
import express from "express";
import { autoRouter } from "../src/routes/auto.js";
import { AnalyticsSettings } from "../src/models/analytics-settings.js";
import { adminAutoRouter } from "../src/routes/admin-auto.js";
import { AutoSettings } from "../src/models/auto-settings.js";
import { SiteConfig } from "../src/models/site-config.js";
import { encryptAutoSecret } from "../src/services/auto-secrets.js";

test("Auto settings: permissions, validation, encrypted secrets and isolated persistence", async () => {
  const previousKey = process.env.GALENO_SETTINGS_ENCRYPTION_KEY;
  const key = "ab".repeat(32); // Test-only key; no real credentials or database.
  let stored: Record<string, unknown> | null = null;
  let writes = 0;
  const originalFind = AutoSettings.findOne;
  const originalUpdate = AutoSettings.findOneAndUpdate;
  const originalConfig = SiteConfig.findOne;
  const originalAnalytics = AnalyticsSettings.findOne;
  let analyticsReads = 0;
  const query = (value: unknown) => ({ select: () => ({ lean: async () => value }) });
  AutoSettings.findOne = (() => query(stored)) as unknown as typeof originalFind;
  AnalyticsSettings.findOne = (() => { analyticsReads++; return query({ measurementId: "G-TESTAUTO" }); }) as unknown as typeof originalAnalytics;
  SiteConfig.findOne = (() => query({ value: "commercial@example.com" })) as unknown as typeof originalConfig;
  AutoSettings.findOneAndUpdate = ((filter: unknown, update: { $set: Record<string, unknown> }) => {
    assert.deepEqual(filter, { slug: "auto" });
    writes++; stored = { ...stored, ...update.$set, slug: "auto" };
    return query(stored);
  }) as unknown as typeof originalUpdate;
  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    const role = req.header("x-test-role");
    req.isAuthenticated = (() => Boolean(role)) as typeof req.isAuthenticated;
    if (role) req.user = { id: "test", name: "test", email: "test@example.com", role: "user", status: "active", roles: [], permissions: role === "manage" ? ["landings.view", "landings.manage"] : role === "view" ? ["landings.view"] : [] };
    next();
  });
  app.use("/admin/auto", adminAutoRouter);
  app.use("/api/auto", autoRouter);
  app.use((error: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => res.status(error.name === "ZodError" ? 400 : 500).json({ error: error.name }));
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>(resolve => server.once("listening", resolve));
  const address = server.address() as { port: number };
  const request = (role?: string, body?: object) => fetch(`http://127.0.0.1:${address.port}/admin/auto`, { method: body ? "PATCH" : "GET", headers: { "Content-Type": "application/json", ...(role ? { "x-test-role": role } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const payload = { sendQuoteEmail: false, sendCommercialEmailOnContract: true, contractRecipientEmail: "auto@example.com", environment: "test", baseUrl: "https://www.gsbeneficios.com.ar/WS-Seguros-desa", username: "test-user", producerCode: "123", commercialPlanCode: "TEST", billingModeCode: "01", paymentConditionCode: "001", paymentMethodCode: "3" };
  try {
    assert.equal((await request()).status, 401);
    assert.equal((await request("none")).status, 403);
    assert.equal((await request("view", payload)).status, 403);
    assert.equal(writes, 0);
    const publicConfig = () => fetch(`http://127.0.0.1:${address.port}/api/auto/config`).then(response => response.json());
    const initial = await publicConfig();
    assert.equal(initial.analytics.enabled, false);
    assert.equal(initial.analytics.measurementId, undefined);
    assert.equal(analyticsReads, 0);
    assert.equal(initial.ready, false);
    delete process.env.GALENO_SETTINGS_ENCRYPTION_KEY;
    assert.equal((await request("manage", { ...payload, password: "test-password" })).status, 503);
    assert.equal(writes, 0);
    assert.equal((await request("manage", { ...payload, contractRecipientEmail: "not-an-email" })).status, 400);
    assert.equal((await request("manage", { ...payload, baseUrl: "http://example.com" })).status, 400);
    process.env.GALENO_SETTINGS_ENCRYPTION_KEY = key;
    const saved = await request("manage", { ...payload, password: "test-password", basicAuthorization: "test-basic" });
    assert.equal(saved.status, 200);
    const output = await saved.json();
    assert.equal(output.settings.hasPassword, true);
    assert.equal(output.settings.hasBasicAuthorization, true);
    assert.equal(JSON.stringify(output).includes("test-password"), false);
    assert.equal("passwordEncrypted" in output.settings, false);
    const encrypted = String(stored!.passwordEncrypted);
    assert.notEqual(encrypted, encryptAutoSecret("test-password"));
    const [, iv, tag, value] = encrypted.split(":");
    const decipher = createDecipheriv("aes-256-gcm", Buffer.from(key, "hex"), Buffer.from(iv, "base64"));
    decipher.setAuthTag(Buffer.from(tag, "base64"));
    assert.equal(Buffer.concat([decipher.update(Buffer.from(value, "base64")), decipher.final()]).toString(), "test-password");
    assert.equal((await request("manage", { ...payload, password: "" })).status, 200);
    assert.equal(stored!.passwordEncrypted, encrypted);
    const read = await (await request("view")).json();
    assert.equal(read.settings.sendQuoteEmail, false);
    assert.equal(read.commercialEmail, "commercial@example.com");
    assert.equal("passwordEncrypted" in read.settings, false);
    assert.equal((await request("manage", { ...payload, analyticsEnabled: true, personTypeCode: "2" })).status, 200);
    const enabled = await publicConfig();
    assert.equal(enabled.analytics.enabled, true);
    assert.equal(enabled.analytics.measurementId, "G-TESTAUTO");
    assert.equal(enabled.personType, "2");
    assert.equal("username" in enabled, false);
    assert.equal("passwordEncrypted" in enabled, false);
    assert.equal((await request("manage", { ...payload, analyticsEnabled: false })).status, 200);
    const disabled = await publicConfig();
    assert.deepEqual(disabled.analytics, { enabled: false });
    assert.equal(analyticsReads, 1);
  } finally {
    server.closeAllConnections();
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
    AutoSettings.findOne = originalFind; AutoSettings.findOneAndUpdate = originalUpdate; SiteConfig.findOne = originalConfig; AnalyticsSettings.findOne = originalAnalytics;
    if (previousKey === undefined) delete process.env.GALENO_SETTINGS_ENCRYPTION_KEY; else process.env.GALENO_SETTINGS_ENCRYPTION_KEY = previousKey;
  }
});
